(sec:numerical_programming)=

# Numerical Programming

Welcome! This notebook is a simple introduction to numerical programming with NumPy.

## Learning goals
By the end of this notebook, you will be able to:
- create and use NumPy arrays,
- explain key differences between arrays and Python lists,
- build numeric grids with `arange` and `linspace`,
- work with multidimensional arrays,
- use `shape`, `reshape`, indexing, and slicing,
- apply basic linear algebra functions in NumPy.

Download the notebook <a href="https://github.com/mitric-lab/python_for_chemists_ss26/blob/main/chapters/crash_course/numerical_programming.ipynb" download>here</a>.

## 0) Importing modules

If a module is already installed, you can import it with:
`import module_name`

In this notebook, we will use the `numpy` module, a powerful tool for numerical computing in Python. For NumPy, the common shortcut is:

In [33]:
import numpy as np

## 1) NumPy arrays vs Python lists

A NumPy array is designed for numerical data.

At beginner level, the key differences are:
- arrays support fast elementwise math like `arr * 2 + 1`,
- arrays have a fixed shape and can be multidimensional,
- lists are general-purpose containers and do not support direct numeric vector operations.


In [34]:
values_list = [1.0, 2.0, 3.0, 4.0]
values_array = np.array(values_list)

print("list:", values_list, type(values_list))
print("array:", values_array, type(values_array))

list: [1.0, 2.0, 3.0, 4.0] <class 'list'>
array: [1. 2. 3. 4.] <class 'numpy.ndarray'>


In [35]:
print("Array arithmetic:", values_array * 2 + 1)

Array arithmetic: [3. 5. 7. 9.]


Note the fundamentally different behavior of lists and arrays:

In [36]:
print(values_list * 2)

[1.0, 2.0, 3.0, 4.0, 1.0, 2.0, 3.0, 4.0]


In [37]:
print(values_list * 2 + 1)

TypeError: can only concatenate list (not "int") to list

Arrays make mathematical workflows cleaner because **one operation can apply to all elements at once**.


## 2) Grids with `arange` and `linspace`

In numerical programming, we often evaluate functions on a grid of x-values.
Grids are useful for tables, plots, approximations, and simulations.

- `np.arange(start, stop, step)` uses a step size.
- `np.linspace(start, stop, num)` uses a number of points.


In [ ]:
grid_a = np.arange(0.0, 1.0, 0.2)
grid_b = np.linspace(0.0, 1.0, 6)

print("arange:", grid_a)
print("linspace:", grid_b)

arange: [0.  0.2 0.4 0.6 0.8]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
y = np.sin(grid_b)
print("x-grid:", grid_b)
print("sin(x):", y)

x-grid: [0.  0.2 0.4 0.6 0.8 1. ]
sin(x): [0.         0.19866933 0.38941834 0.56464247 0.71735609 0.84147098]


Note: `linspace` includes the endpoint by default, while `arange` usually stops before `stop`.


## 3) Two- and multidimensional arrays

NumPy arrays generalize vectors and matrices to arbitrary dimensions. A 1D array is like a vector. A 2D array is like a matrix (rows and columns). A 3D array adds another axis (for example, a stack of matrices) and so on.

In [ ]:
v = np.array([1, 2, 3, 4])
M = np.array([[1, 2, 3], [4, 5, 6]])
T = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("v ndim:", v.ndim, "shape:", v.shape)
print("M ndim:", M.ndim, "shape:", M.shape)
print("T ndim:", T.ndim, "shape:", T.shape)

v ndim: 1 shape: (4,)
M ndim: 2 shape: (2, 3)
T ndim: 3 shape: (2, 2, 2)


## 4) `shape` and `reshape`

The `shape` of an array tells you its size along each axis.
Use `reshape` to reorganize the same data into a different shape.
The total number of elements must stay the same.


In [ ]:
a = np.arange(12)
print("a:", a)
print("shape:", a.shape)

a: [ 0  1  2  3  4  5  6  7  8  9 10 11]
shape: (12,)


In [ ]:
A = a.reshape(3, 4)
print(A)
print("shape:", A.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4)


In [ ]:
B = a.reshape(2, -1)
print(B)
print("shape:", B.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
shape: (2, 6)


Using `-1` lets NumPy infer one dimension automatically.


## 5) Indexing NumPy arrays

Indexing lets you access one element at a specific position.

- In 1D: `x[i]`
- In 2D: `X[row, col]`
- Negative indices count from the end.


In [ ]:
x = np.array([10, 20, 30, 40])
print("x[0] =", x[0])
print("x[-1] =", x[-1])

x[0] = 10
x[-1] = 40


In [ ]:
X = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(X)
print("X[1, 2] =", X[1, 2])
print("row 0:", X[0, :])
print("column 1:", X[:, 1])

[[11 12 13]
 [21 22 23]
 [31 32 33]]
X[1, 2] = 23
row 0: [11 12 13]
column 1: [12 22 32]


## 6) Slicing arrays

Slicing extracts parts of an array using:
`start:stop:step`

- `start` is included.
- `stop` is excluded.
- `step` controls spacing.

In [ ]:
s = np.arange(10)
print("s:", s)
print("s[2:7] =", s[2:7])
print("s[:5] =", s[:5])
print("s[5:] =", s[5:])
print("s[::2] =", s[::2])
print("s[::-1] =", s[::-1])

s: [0 1 2 3 4 5 6 7 8 9]
s[2:7] = [2 3 4 5 6]
s[:5] = [0 1 2 3 4]
s[5:] = [5 6 7 8 9]
s[::2] = [0 2 4 6 8]
s[::-1] = [9 8 7 6 5 4 3 2 1 0]


Let's use one fixed matrix with values `11, 12, 13, ...` so slice results are easy to read.

In [ ]:
S = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
])
print(S)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]


In [ ]:
print("first two rows, first three cols:\n", S[:2, :3])

first two rows, first three cols:
 [[11 12 13]
 [21 22 23]]


In [ ]:
print("rows 1..end, cols 2..end:\n", S[1:, 2:])

rows 1..end, cols 2..end:
 [[23 24 25]
 [33 34 35]
 [43 44 45]]


In [ ]:
print("every second row:\n", S[::2, :])

every second row:
 [[11 12 13 14 15]
 [31 32 33 34 35]]


In [ ]:
print("every second col:\n", S[:, ::2])

every second col:
 [[11 13 15]
 [21 23 25]
 [31 33 35]
 [41 43 45]]


In [ ]:
print("reverse rows and columns:\n", S[::-1, ::-1])

reverse rows and columns:
 [[45 44 43 42 41]
 [35 34 33 32 31]
 [25 24 23 22 21]
 [15 14 13 12 11]]


Slicing usually returns a **view** in NumPy (not a full copy). So changing the slice can also change the original array.

In [ ]:
S_view = S[:2, :2]
S_view[0, 0] = 999
print("S_view:\n", S_view)
print("S changed too:\n", S)

S_view:
 [[999  12]
 [ 21  22]]
S changed too:
 [[999  12  13  14  15]
 [ 21  22  23  24  25]
 [ 31  32  33  34  35]
 [ 41  42  43  44  45]]


In [ ]:
S_copy = S[:2, :2].copy()
S_copy[0, 0] = -1
print("S_copy:\n", S_copy)
print("S stays unchanged by S_copy edit:\n", S)

S_copy:
 [[-1 12]
 [21 22]]
S stays unchanged by S_copy edit:
 [[999  12  13  14  15]
 [ 21  22  23  24  25]
 [ 31  32  33  34  35]
 [ 41  42  43  44  45]]


## 7) Basic linear algebra with NumPy

We now use NumPy for basic linear algebra operations.


### Dot product and matrix multiplication

- `np.dot(u, v)` for dot products and matrix products.
- `@` is matrix multiplication syntax.
- `*` is elementwise multiplication.


In [ ]:
u = np.array([1.0, 2.0, 3.0])
v = np.array([4.0, 5.0, 6.0])
print("dot(u, v) =", np.dot(u, v))

dot(u, v) = 32.0


In [ ]:
A = np.array([[1.0, 2.0], [3.0, 4.0]])
B = np.array([[2.0, 0.0], [1.0, 2.0]])

print("A @ B:\n", A @ B)
print("np.dot(A, B):\n", np.dot(A, B))
print("A * B (elementwise):\n", A * B)

A @ B:
 [[ 4.  4.]
 [10.  8.]]
np.dot(A, B):
 [[ 4.  4.]
 [10.  8.]]
A * B (elementwise):
 [[2. 0.]
 [3. 8.]]


### Norms

A norm measures vector or matrix size.
- For a 1D vector, default norm is Euclidean length.
- For a 2D matrix, default norm is Frobenius norm.


In [ ]:
w = np.array([3.0, 4.0])
print("norm(w) =", np.linalg.norm(w))

Q = np.array([[1.0, 2.0], [3.0, 4.0]])
print("Frobenius norm of Q =", np.linalg.norm(Q))
print("row norms =", np.linalg.norm(Q, axis=1))

norm(w) = 5.0
Frobenius norm of Q = 5.477225575051661
row norms = [2.23606798 5.        ]


### Eigenvalues and eigenvectors with `np.linalg.eigh`

Use `eigh` for symmetric matrices.
If `M` is symmetric, `eigh` returns:
- eigenvalues (1D array),
- eigenvectors (columns of a matrix).


In [ ]:
R = np.array([[2.0, -1.0], [3.0, 0.0]])
M = R + R.T  # symmetric matrix

eigvals, eigvecs = np.linalg.eigh(M)
print("M:\n", M)
print("eigenvalues:", eigvals)
print("eigenvectors (columns):\n", eigvecs)

M:
 [[4. 2.]
 [2. 0.]]
eigenvalues: [-0.82842712  4.82842712]
eigenvectors (columns):
 [[ 0.38268343 -0.92387953]
 [-0.92387953 -0.38268343]]


## 8) Recap

You learned how to:
- create NumPy arrays and compare them to lists,
- build numerical grids with `arange` and `linspace`,
- handle multidimensional arrays with `shape` and `reshape`,
- index and slice arrays in detail,
- use `dot`, `@`, `linalg.norm`, and `linalg.eigh`.


## 9) Mini practice

Try these tasks:
1. Create a grid from 0 to 2 with 9 points using `linspace`, then compute `np.cos(grid)`.
2. Create `np.arange(1, 13)` and reshape it into shape `(3, 4)`.
3. From matrix `S`, extract the middle 2x3 block with slicing.
4. Create two vectors and compute their dot product.
5. Build a symmetric 2x2 matrix and run `np.linalg.eigh`.
